"""make guild_id nullable for PM subscriptions

Revision ID: 0b4d25693294
Revises: fa82809801f1
Create Date: 2025-06-23 23:12:33.679520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4d25693294'
down_revision: Union[str, None] = 'fa82809801f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'guild_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
