"""change last_ran to bigint epoch

Revision ID: 321e1f84eced
Revises: f4378b1068d1
Create Date: 2025-06-25 11:59:09.831081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "321e1f84eced"
down_revision: Union[str, None] = "f4378b1068d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "last_ran",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        postgresql_using="EXTRACT(EPOCH FROM last_ran)::bigint",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "last_ran",
        existing_type=sa.BigInteger(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
