"""Add toggle for twitter obfs

Revision ID: 3c79d62144a9
Revises: c72a1dcb408e
Create Date: 2025-10-09 15:22:56.903848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c79d62144a9"
down_revision: Union[str, None] = "c72a1dcb408e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add twitter_obfuscate column with server default for existing rows
    op.add_column(
        "guilds",
        sa.Column(
            "twitter_obfuscate", sa.Boolean(), server_default="false", nullable=False
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guilds", "twitter_obfuscate")
    # ### end Alembic commands ###
