"""add last_reported_id to subscription

Revision ID: 4ff9ee3e2ed2
Revises: 3261dcfb83c9
Create Date: 2025-06-23 17:00:25.391503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff9ee3e2ed2'
down_revision: Union[str, None] = '3261dcfb83c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('last_reported_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'last_reported_id')
    # ### end Alembic commands ###
