"""Add new holes obj

Revision ID: 63fceb2f70d9
Revises: 321e1f84eced
Create Date: 2025-07-24 12:14:25.542144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63fceb2f70d9"
down_revision: Union[str, None] = "321e1f84eced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("forwarded_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("is_pm", sa.Boolean(), nullable=False),
        sa.Column("anonymize", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("holes")
    # ### end Alembic commands ###
