"""add filters and is_pm to subscription

Revision ID: fa82809801f1
Revises: 4ff9ee3e2ed2
Create Date: 2025-06-23 22:55:16.232400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa82809801f1"
down_revision: Union[str, None] = "4ff9ee3e2ed2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("filters", sa.String(), nullable=True))
    op.add_column(
        "subscriptions",
        sa.Column("is_pm", sa.Boolean(), nullable=True, server_default=sa.false()),
    )
    op.alter_column("subscriptions", "is_pm", nullable=False)
    op.alter_column("subscriptions", "is_pm", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "is_pm")
    op.drop_column("subscriptions", "filters")
    # ### end Alembic commands ###
