# hole_config.yaml

static:
  - ["1993273647727372", "27364737747874"]

dynamic:
  - myServer1:
    chan_id: "27364863847"
    users:
      - myUser1:
        user_id: "48347276774323663"
        fluff: "This user is blah blah blah..."
      - myUser2:
        user_id: "17364674782773"
        fluff: "This user is blah blah blah..."
