name: FOPS Bot CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_FOPS: ghcr.io/snowsune/fops-bot
  IMAGE_YTDLP: ghcr.io/snowsune/yt-dlp-service

jobs:
  # test:
  #   name: Pytest the Bot
  #   runs-on: ubuntu-latest
  #   needs: [formatblack, build-and-publish-image]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1
  #     - name: Test the bot image
  #       run: export TAG=main && docker compose -f docker-compose.yml run fops_bot test
  #     - name: Discord notification
  #       if: ${{ failure() }}
  #       env:
  #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #       uses: Ilshidur/action-discord@master
  #       with:
  #         args: "FopsBot Pytest failed!"

  formatblack:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

      # - name: Fail if actions taken
      #   if: steps.action_black.outputs.is_formatted == 'true'
      #   run: exit 1

      # - name: Discord notification
      #   if: ${{ failure() }}
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     args: "Black formatter reported errors in {{ EVENT_PAYLOAD.pull_request.html_url }} !"

  build-and-publish-image:
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest
    needs: [formatblack]
    strategy:
      matrix:
        include:
          - service: fops_bot
            context: ./fops_bot
            image: ghcr.io/snowsune/fops-bot
            notify_name: Fops Bot
            dockerfile: ./fops_bot/Dockerfile
          - service: yt_dlp_service
            context: ./yt_dlp_service
            image: ghcr.io/snowsune/yt-dlp-service
            notify_name: yt-dlp Service
            dockerfile: ./yt_dlp_service/Dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Sanitize branch name for tag
        id: vars
        run: |
          BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV

      - name: Check for changes in service directory
        id: changes
        run: |
          # For PRs, compare against the base branch
          # For pushes, compare against the previous commit
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            echo "Checking changes in PR against base: $BASE_SHA"
            CHANGED_FILES=$(git diff --name-only $BASE_SHA...HEAD)
          else
            # For push events, check against previous commit
            BASE_SHA="HEAD~1"
            echo "Checking changes in push against previous commit"
            CHANGED_FILES=$(git diff --name-only HEAD~1)
          fi
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Check if any files in the service directory have changed
          if echo "$CHANGED_FILES" | grep -q "^${{ matrix.service }}/"; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
            echo "Changes detected in ${{ matrix.service }}"
          # Also build if shared files changed (docker-compose, CI config, etc.)
          elif echo "$CHANGED_FILES" | grep -qE "^(docker-compose\.yml|\.github/|README\.md)$"; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
            echo "Shared files changed, building ${{ matrix.service }}"
          else
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
            echo "No changes detected in ${{ matrix.service }}"
          fi

      - name: Log in to GitHub Container Registry
        if: steps.changes.outputs.HAS_CHANGES == 'true' || github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.changes.outputs.HAS_CHANGES == 'true' || github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ env.BRANCH_TAG }}

      - name: Skip build notification
        if: steps.changes.outputs.HAS_CHANGES == 'false' && github.event_name != 'push'
        run: |
          echo "Skipping build for ${{ matrix.notify_name }} - no changes detected"

      - name: Get Docker image size
        if: steps.changes.outputs.HAS_CHANGES == 'true' || github.event_name == 'push'
        id: image_size
        run: |
          SIZE=$(docker images ${{ matrix.image }}:latest --format "{{.Size}}")
          echo "IMAGE_SIZE=$SIZE" >> $GITHUB_ENV

      - name: Discord notification
        if: (steps.changes.outputs.HAS_CHANGES == 'true' || github.event_name == 'push') && success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: ncatelli/action-discord@115-add-wait-parameter-prefix
        with:
          args: "Built and published a new ${{ matrix.notify_name }} docker image to `${{ matrix.image }}:latest` and `${{ matrix.image }}:${{ env.BRANCH_TAG }}`! Image size: `${{ env.IMAGE_SIZE }}`"
